[package]
name = "line_prefixer"
version = "0.1.0"
edition = "2024"
authors = ["Dima P <dimapm@pm.me>"]
license = "MIT"
description = "Crate to add prefix to the lines when it used with other writers"
readme = "README.md"
homepage = "https://github.com/di-rs/clis/line_prefixer"
repository = "https://github.com/di-rs/clis/line_prefixer"
keywords = ["line_prefixer", "prefix", "writer", "line_prefixer"]
categories = ["writer", "prefix"]

[dev-dependencies]
pretty_assertions = "1.4.1"

[lints]
workspace = true
