[workspace]
resolver = "3"
members = ["biggie","bool", "calr", "catr", "commr", "cutr", "echor", "findr", "grepr", "headr", "kara", "lsr", "tailr", "uniqr", "utils/error", "utils/logging", "wcr"]

[workspace.package]
authors = ["Dima P <dimapm@pm.me>"]
edition = "2024"
license = "MIT"
repository = "https://github.com/di-rs/clis"
readme = "README.md"
include = ["README.md", "LICENSE", "build.rs", "Cargo.toml", "src/**/*.rs"]

[workspace.dependencies]
clap = { version = "4.6", features = ["derive"] }
color-eyre = { version = "0.6" }
clap-verbosity-flag = "3"
log = "0.4"

exitcode = "1.1.2"
thiserror = "2.0.20"
assert_cmd = "2.2.2"
assert_fs = "1.1.4"
predicates = "3.1.4"
pretty_assertions = "1.4.1"

[workspace.lints.clippy]
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"
indexing_slicing = "deny"
arithmetic_side_effects = "deny"
unreachable = "deny"
unimplemented = "deny"
unchecked_time_subtraction = "deny"
todo = "deny"
string_slice = "deny"
panic_in_result_fn = "deny"
panic = "deny"
exit = "deny"
as_conversions = "deny"
