[package]
name = "clis-fuzz"
version = "0.0.0"
edition = "2024"
license = "MIT"
publish = false

[package.metadata]
cargo-fuzz = true

[workspace]
members = ["."]

[dependencies]
libfuzzer-sys = "0.4"
parsu = { path = "../../parsu" }
tailr = { path = "../../coreutils/tailr" }

[[bin]]
name = "parsu_xml"
path = "fuzz_targets/parsu_xml.rs"
test = false
doc = false
bench = false

[[bin]]
name = "tail_bytes"
path = "fuzz_targets/tail_bytes.rs"
test = false
doc = false
bench = false
