[package]
name = "biggie"
version = "0.1.0"
description = "A tool to generate large files"
homepage = "https://github.com/di-rs/clis/grep"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
include.workspace = true

[dependencies]
clap = { workspace = true }
color-eyre = { workspace = true }
clap-verbosity-flag = { workspace = true }
log = { workspace = true }
error = { path = "../utils/error" }
logging = { path = "../utils/logging" }
thousands = "0.2.0"
rand = "0.10.3"

[dev-dependencies]
assert_cmd = { workspace = true }
assert_fs = { workspace = true }
predicates = { workspace = true }

[lints]
workspace = true
