[package]
name = "biggie"
version = "0.1.0"
description = "A tool to generate large files"
homepage = "https://github.com/di-rs/clis/grep"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
include.workspace = true

[features]
default = ["csv"]
csv = ["dep:csv"]

[dependencies]
csv = { workspace = true, optional = true }
clap = { workspace = true }
anyhow.workspace = true
tracing.workspace = true
cli-tracing = { path = "../utils/cli-tracing" }
log.workspace = true
thousands = "0.2.0"
rand = "0.10.3"

[dev-dependencies]
tracing-subscriber = { workspace = true, features = ["json"] }
serde_json.workspace = true
assert_cmd = { workspace = true }
assert_fs = { workspace = true }
predicates = { workspace = true }

[lints]
workspace = true
