[package]
name = "error"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
include.workspace = true

[dependencies]
color-eyre = { workspace = true }
clap-verbosity-flag = { workspace = true }
log = { workspace = true }

[lints]
workspace = true
