[package]
name = "grepr"
version = "0.1.0"
description = "A tool to search files"
homepage = "https://github.com/di-rs/clis/grep"
keywords = ["cli", "search", "demo"]
categories = ["command-line-utilities"]
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
include.workspace = true

[dependencies]
clap = { workspace = true }
regex = "1.10.3"
walkdir = "2.4.0"
thiserror = "2.0.20"
clap-verbosity-flag = "3.0.4"
exitcode = "1.1.2"
ctrlc = "3.5.2"
env_logger = "0.11.11"
human-panic = "2.0.8"
log = "0.4.33"
line_prefixer = "0.1.0"

[dev-dependencies]
assert_cmd = "2.0.13"
predicates = "3.0.4"
pretty_assertions = "1.4.0"
assert_fs = "1.1.4"

[build-dependencies]
clap_mangen = "0.3.0"
clap = { workspace = true }
clap-verbosity-flag = "3.0.4"
regex = "1.10.3"
thiserror = "2.0.20"

[lints]
workspace = true
